services:
  # The Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:5000/test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - dev-network

  # The Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://frontend:5173/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
