services:
  # The Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # The 'ports' section for the backend can be removed!
    # The frontend will access it via the internal Docker network.
    volumes:
      - ./backend:/app

  # The Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      # We still need to access the Vite server from our browser
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # The 'environment' section is no longer needed here.
    depends_on:
      - backend
